const BACKGROUND_PRIMARY = "#121212"
const BACKGROUND_SECONDARY = "#212121"

const DISPLAY_OUTLINE = "#424242"

const ICON_COLOR = "#C6C6C6"
const ICON_COLOR_SUCCESS = "#85C990"
const ICON_COLOR_DANGER = "#D32F2F"

const TITLE_COLOR = "#C6C6C6"
const SUBTITLE_COLOR = "#818181"

const BUTTON_COLOR_PRIMARY = "#85C990"
const TEXT_BUTTON_COLOR_PRIMARY = "#FFFFFF"
const ERROR_BUTTON_COLOR = "#D32F2F"

const PAGINATION_DOT_COLOR = "#FAFAFA"
const PAGINATION_DOT_ACTIVE_COLOR = "#FFFFFF"

const colorType = {BACKGROUND_PRIMARY,
  BACKGROUND_SECONDARY,
  ICON_COLOR,
  ICON_COLOR_SUCCESS,
  ICON_COLOR_DANGER,
  TITLE_COLOR,
  SUBTITLE_COLOR,
  PAGINATION_DOT_COLOR,
  PAGINATION_DOT_ACTIVE_COLOR,
  DISPLAY_OUTLINE,
  BUTTON_COLOR_PRIMARY,
  TEXT_BUTTON_COLOR_PRIMARY,
  ERROR_BUTTON_COLOR,}

export {colorType};
